### ISSUE TITLE
Provide Access to the Section Header

### ISSUE THREAD

**Issue by masterofjellyfish** [konrad-kruczynski/elfsharp#27]
At the moment, one cannot access the section header via API. If I want to get, for example, the file offset of a Section, I currently have to use reflection to get that:

```csharp
foreach (PropertyInfo property in typeof(Section<long>).GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public))
{
    if (property.Name == "Header")
    {
        foreach (PropertyInfo p in property.GetValue(s).GetType().GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public))
        {
            if (p.Name == "Offset")
            {
                FileOffset = (long)p.GetValue(property.GetValue(s));
            }
        }
    }
}
```

This just doesn't feel right.

**Comment by konrad-kruczynski** [comment]
Hey, you're right. But generally most of the properties that can be obtained from section header are accessible from the `Section<T>` class. Note that header always contains "widest" data type for the given property while section converts it to type of the concrete ELF. `Offset` however is not - yet - available. But I'm happy to add it. Would such solution satisfy you? Other missing properties could be added as well.

**Comment by masterofjellyfish** [comment]
Hey,

if you wrap it like the other properties, that's totally fine. I need it to map the loaded section offsets (read: xrefs) to file offsets, so, getting that via the section header is totally fine.

**Comment by konrad-kruczynski** [comment]
Hi, I've finally added the Offset property to `ELF<T>` class :)

**Comment by masterofjellyfish** [comment]
awesome thanks :)
