### ISSUE TITLE
Ambiguous calls

### ISSUE THREAD

**Issue by csholmq** [konrad-kruczynski/elfsharp#29]
Trying out a simple example, using VS Express 2015 and targeting .NET 4.5:

```c#
using ELFSharp.ELF;
using ELFSharp.ELF.Sections;
using System;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Windows.Forms;

...

var elf = ELFReader.Load(elfFile);
var symbols = ((ISymbolTable)elf.GetSection(".symtab")).Entries.Where(x => x.Type == SymbolType.Object);
```

But I can't seem to get past this weird "call is ambiguous". The calls look identical to me.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Where<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)' and 'System.Linq.Enumerable.Where<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)'	Elf-Parser	C:\dev\Elf-Parser\Form1.cs	30	Active

Any idea on what this could be?

**Comment by csholmq** [comment]
Found the issue. Latest version (0.1.0) on NuGet is the LinqBridge release. I uninstalled and installed 0.0.11 instead.

@konrad-kruczynski Would you mind releasing a new (non LinqBridge) version to NuGet?

**Comment by konrad-kruczynski** [comment]
I see. There should be such version, but maybe it is wrongly packed. Anyway, I plan to drop the support for the LinqBridge version since it is not really updated and I do not have time to maintain it. I'll try to look at this today but since the week has been quite busy so far it might as well happen by the end of it. Stay tuned :)

**Comment by csholmq** [comment]
Dropping LinqBridge should work. Don't know anyone running < 3.0.

**Comment by konrad-kruczynski** [comment]
The newest package is in the nuget gallery now.
