### ISSUE TITLE
Strong-named assembly in NuGet package

### ISSUE THREAD

**Issue by bastianeicher** [konrad-kruczynski/elfsharp#32]
It would be great if you could add a [strong-named](https://msdn.microsoft.com/en-us/library/wd40t7ad) assembly to the NuGet release of the library. That way ELFSharp could be referenced in projects that are themselves strong-named.

**Comment by konrad-kruczynski** [comment]
Good point, why not. I'll try to take care of this soon.

**Comment by konrad-kruczynski** [comment]
Maybe not so soon, but eventually done :)

**Comment by bastianeicher** [comment]
Awesome, thanks. :)

I'll be re-targeting the [Zero Install Publishing Tools](https://0install.de/docs/publishing/tools/) to .NET 4.0 using your new NuGet release soon.
