### ISSUE TITLE
How to get offset of a segment?

### ISSUE THREAD

**Issue by tathanhdinh** [konrad-kruczynski/elfsharp#33]
Hi everyone,
I am trying to figure out how to get the file offset of a segment in an ELF. I observe that the field `offset` in `Segment` has `private` attribute, so the only way to get `offset` is to parse again the header of this segment? Is there some reason to make `offset` as `private`?
Many thanks.

**Comment by konrad-kruczynski** [comment]
It can be done, no problem, I just have to find some time to do it - which should happen soon.

**Comment by konrad-kruczynski** [comment]
Alternatively you can code the proposed solution and send here as a PR.

**Comment by konrad-kruczynski** [comment]
It's now done and available on nuget.
