### ISSUE TITLE
Extract pointer size

### ISSUE THREAD

**Issue by csholmq** [konrad-kruczynski/elfsharp#34]
I am trying to extract information regarding the target platform from the ELF file. `Architecture`, `Endianess` and `EntryPoint` are all easy to grab. But what about pointer size? 

E.g `Class` only takes values `Bit32` or `Bit64`, so I assume that isn't it since it doesn't cover 16 bit architectures.

**Comment by konrad-kruczynski** [comment]
Interesting question. I would say that originally the ELF format was designed for 32 bit platforms and later extended for 64 bit ones. But it may be that it was later fitted for smaller (e.g. embedded architectures). Perhaps you have a sample file for such architecture (or at least an architecture so I could look up some specifications).

**Comment by csholmq** [comment]
So it seems. Bit odd.

No, I don't have an ELF aimed towards a 16 bit system at hand right now. I will look for one though.

**Comment by csholmq** [comment]
I got a hold of an ELF for a DSP56 16 bit processor. It appears to be listed as Bit32. 

Also, could only find a single .debug sector. Weird.
