### ISSUE TITLE
ELFSharp NetStandard Package includes netstandard .dlls

### ISSUE THREAD

**Issue by Evmaus-MS** [konrad-kruczynski/elfsharp#39]
Hey:

It looks like due to an issue with NuGetizer (https://github.com/NuGet/Home/issues/6270), the entire netstandard set of libraries is included in the NuGet package.  This isn't an issue if you're consuming the library via .NET Core, but it will cause numerous build conflicts with the standard libraries if you try to consume the library in .NET 4.6.1 (which should be possible).

It should be possible to build the NuGet package from the CSProj file without NuGetizer via `dotnet pack ELFSharp.csproj` (see:  https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x), which seems to avoid including all of the dependencies and removes the dependency on a nonstandard tool, and seems to correctly version/set authors/etc.

--Everett Maus

**Comment by konrad-kruczynski** [comment]
Very good point. I didn't notice that the package weights about 3MB which should be suspicious on its own. However, I have just tried using `dotnet pack` and the result is somewhat smaller (1.9MB), but still contains a lot of libraries. Is it the result you expected?

**Comment by Evmaus-MS** [comment]
Not quite--I'd expect the NuGet to just contain ELFSharp.dll.

I just double checked--you have to remove the NuGetizer reference completely to get the NuGet package with just the .dll.

**Comment by konrad-kruczynski** [comment]
Turns out that I didn't really understand your comment with NuGetizer. Thanks for the comment, I've just uploaded fixed package (version 1.1.1).

**Comment by Evmaus-MS** [comment]
Awesome--works great now with Net 4.6.1 (as well as .Net Core).

**Comment by konrad-kruczynski** [comment]
Exactly.
