### ISSUE TITLE
ELF:  Support for parsing the Dynamic Section

### ISSUE THREAD

**Issue by Evmaus-MS** [konrad-kruczynski/elfsharp#43]
It'd be useful for a project I'm working on that consumes ELFSharp (BinSkim -- https://github.com/Microsoft/binskim ) if ELFSharp could parse the Dynamic section of an ELF binary--we need to check some parts of that section in order to implement a check.

If you'd like, I can put together a PR with an implementation and send it over.

**Comment by konrad-kruczynski** [comment]
Parsing dynamic section could definitely see some use and PR would surely be nice to see :)

**Comment by motianlun1111** [comment]
This Elfsharp is very good, but i am a freshman and if this project has a user manual that will be greater. Now i always do not know which workspace to use, and i want to load all the symbols and address of those symbols, but i do not know how to do it. the examples is too less.
by the way, can this Lib show the details of some structure symbols?
so appreciated you can share such a good thing.

**Comment by konrad-kruczynski** [comment]
@motianlun1111 Please create a separate ticket to discuss that problem and describe what do you need specifically.

**Comment by konrad-kruczynski** [comment]
This can now be closed.
