### ISSUE TITLE
segment.GetMemoryContents() returns partly gibberish when Size > FileSize

### ISSUE THREAD

**Issue by gralpli** [konrad-kruczynski/elfsharp#45]
If the `FileSize` of a segment is smaller than its `Size`, the part of the data that is not in the ELF should be filled up with zeroes, I think.

**Steps to reproduce:**
1. Create an ELF file with a segment that has a `FileSize` smaller than `Size`.
2. Call `GetFileContents()` and `GetMemoryContents()` on this segment.

**Expected result:**
Let's assume the FileSize is 4 and the Size is 8. Then `GetFileContents()` should return something like
`new byte[] { 0xZZ, 0xZZ, 0xZZ, 0xZZ }`
where `0xZZ` is any number
and `GetMemoryContents()` should return something like
`new byte[] { 0xZZ, 0xZZ, 0xZZ, 0xZZ, 0x00, 0x00, 0x00, 0x00 }`

**Actual result:**
`GetFileContents()` returns
`new byte[] { 0xZZ, 0xZZ, 0xZZ, 0xZZ }`
`GetMemoryContents()` returns
`new byte[] { 0xZZ, 0xZZ, 0xZZ, 0xZZ, 0xGG, 0xGG, 0xGG, 0xGG }`
where 0xGG are random numbers

Version I used: 2.1.0

**Comment by konrad-kruczynski** [comment]
I can confirm the bug, I'll add a test and a fix it. Sorry for so late response.

**Comment by konrad-kruczynski** [comment]
Should be fixed with 2.1.1. Please test.
