### ISSUE TITLE
Expose Header Properties

### ISSUE THREAD

**Issue by FZFalzar** [konrad-kruczynski/elfsharp#50]
Is there any way to access the properties of e.g Section Header like Start Address/Size like how the Section.ToString() method prints out the following:

`text: ProgBits, load @0x3A02C0, 39796240 bytes long`

So that one can access it by the following: mySection.Address, mySection.Size

Currently I am splitting this string manually and it is unwieldy.

**Comment by konrad-kruczynski** [comment]
This is available, but only from specific ELF classes (not `IELF` interface that covers 32-bit and 64-bit binaries). Please look at http://elfsharp.turtleware.eu/examples.shtml#bit32 and tell me if it answers your question.

**Comment by FZFalzar** [comment]
Yes it did, didn't think of opening the link at the front page since usually I'd refer to github's wiki or Readme.md for quick docs especially when dealing with plugins/libraries on different languages. Thanks! Closing issue.
