### ISSUE TITLE
Sections / segments count

### ISSUE THREAD

**Issue by dnezamaev** [konrad-kruczynski/elfsharp#60]
Hi. Cannot find way to get number of sections and segments count. Looks like they are stored in sectionHeaderEntryCount and segmentHeaderEntryCount, but fields are private and have no getters. Is there another way to get info? If no, suggesting to add public getter to all data from global elf header =)

**Comment by konrad-kruczynski** [comment]
Hi @dnezamaev,
I have just implemented and committed a small improvement. `Sections` and `Segments` properties are now of type `IReadOnlyList` instead of `IEnumerable`, so now you should be able to get sections count easily by `elf.Sections.Count`.

**Comment by konrad-kruczynski** [comment]
This should soon be available on nuget as version 2.5.
