### ISSUE TITLE
Add visibility to symbols

### ISSUE THREAD

**Issue by nattthebear** [konrad-kruczynski/elfsharp#71]
As documented [here](https://refspecs.linuxbase.org/elf/gabi4+/ch4.symtab.html), the byte after `info`, referenced at https://github.com/konrad-kruczynski/elfsharp/blob/master/ELFSharp/ELF/Sections/SymbolTable.cs#L44 contains information about the visibility of the symbol.  I would like to see that information exposed in the public API.

**Comment by konrad-kruczynski** [comment]
Fixed, version 2.10 will be pushed to the nuget soon.

**Comment by nattthebear** [comment]
Thank you! 😄
