### ISSUE TITLE
ELFReader methods do not always close streams

### ISSUE THREAD

**Issue by ljusten** [konrad-kruczynski/elfsharp#91]
If shouldOwnStream is true, the methods should close the stream if loading fails. Otherwise, for instance ELFReader.TryLoad(filename, out IELF elf) won't close the stream if the file is not an ELF file.

**Comment by konrad-kruczynski** [comment]
[ELFSharp 2.16.1](https://www.nuget.org/packages/ELFSharp/2.16.1) published, closing ticket.

**Comment by ljusten** [comment]
Thanks!
