### ISSUE TITLE
Analysis on the definition of symbolic structure

### ISSUE THREAD

**Issue by cfh763551832** [konrad-kruczynski/elfsharp#95]
Can this library parse out the struct definition for one of these symbols, and if not, how can I solve it.
The following is the ELF file that I use IDA pro tool to parse, which can parse out the structure definition corresponding to the symbol, can we achieve this function in this library? Below is the screenshot.looking forward to your reply,thank you.
![1](https://github.com/konrad-kruczynski/elfsharp/assets/21970995/cbdace1a-ea9a-42e4-a6fc-a78d571a3679)
![2](https://github.com/konrad-kruczynski/elfsharp/assets/21970995/faf8bb0a-d214-44dd-967a-a01cb2f61fc3)
![3](https://github.com/konrad-kruczynski/elfsharp/assets/21970995/7e541ddb-6be6-475a-9faa-11cb3c98806c)

**Comment by konrad-kruczynski** [comment]
No, this is not possible. The ELF structure does not contain necessary information, you may have more luck with DWARF data, but this is not what is expected to be supported within this library.

**Comment by cfh763551832** [comment]
> No, this is not possible. The ELF structure does not contain necessary information, you may have more luck with DWARF data, but this is not what is expected to be supported within this library.

Thanks for your reply, I have parsed it with the libdwarf library
